create table products (
    id bigint generated by default as identity (start with 1),
    name varchar(50) not null,
    priceInPounds real,
    offerApplied bit,
    primary key (id),
    unique (name));
